### ISSUE TITLE
DriveTrain should use followers rather than SpeedControllerGroup.

### ISSUE THREAD

**Issue by MC42** [FRC1257/2019-Robot#1]
Use of SpeedControllerGroup individually commands both motors to a given output, and in the event we'd like to use the more advanced features of the speed controller (PID, closed loop anything, etc.), we'd need to move away from SpeedControllerGroup anyways.  

Use the CANSparkMax follower command and have the rear motors follow the front ones.

**Comment by A-i-Y-a** [comment]
Got you, will do.
