### ISSUE TITLE
IntakeArm.restrictMotion() Prevents the Arm from Moving

### ISSUE THREAD

**Issue by zbreit** [FRC1257/2019-Robot#6]
The current code to restrict the arm motion prevents the intake from moving in any direction if either limit switch is pressed.
https://github.com/FRC1257/2019-Robot/blob/b0d8c30239f494b8937fae59b7beb91987a16a94/src/main/java/frc/subsystems/IntakeArm.java#L46-L54
We may want to rework how this function works so that we can still move the arm away from the limit switches.

**Comment by MC42** [comment]
Okay so minor thing to note, limit switches on a motor controller are in _hardware_ not software, and I don't believe we specified any mechanisms to have limit switches anyways.
