### ISSUE TITLE
"SmartCurrentLimit" on Drivetrain

### ISSUE THREAD

**Issue by MC42** [FRC1257/2019-Robot#7]
https://github.com/FRC1257/2019-Robot/blob/DriveTrain/src/main/java/frc/subsystems/DriveTrain.java#L47

The setSmartCurrentLimit() method has a input where you simply input a current limit, and as-is we're setting a current limit, free current limit, and a rpm to not overcome.  We should make sure to empirically test this rpm limit, and determine whether it's actually needed or not as it's documentation seems to suggest it decreases the overall linearity of the system.

**Comment by A-i-Y-a** [comment]
Will test when I can. I don't think it's necessary, as it's an RPM floor not a ceiling.

**Comment by MC42** [comment]
We want to be able to stop, so setting a RPM floor isn't a good idea :stuck_out_tongue:
